spring:
  datasource:
    url: jdbc:postgresql://database-fs-restaurant.cdnkrvkiwrsm.eu-west-2.rds.amazonaws.com:5432/DB_FS_USERDETAILS
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/