server:
  port: 9094
  
spring:
  profiles:
    active: dev

    
  application:
    name: USERDETAILS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql